// Code generated by goapi. DO NOT EDIT.
package server

import (
	"fmt"
)

type ValidationError struct {
	Type  string
	In    string
	Field string
	Err   error
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("Validation error %s for field %s in %s", e.Type, e.Field, e.In)
}
func (e *ValidationError) Unwrap() error { return e.Err }
