// Code generated by goapi. DO NOT EDIT.
package server

// #/components/schemas/Error
type Error struct {
	Code    int    `json:"code" validate:"required"`
	Message string `json:"message" validate:"required"`
}

// #/components/schemas/ListPetsQuery
type ListPetsQuery struct {
	Limit *int `query:"limit" validate:"omitempty,lte=100"`
}

// #/components/schemas/Pet
type Pet struct {
	ID   int     `json:"id" validate:"required"`
	Name string  `json:"name" validate:"required"`
	Tag  *string `json:"tag,omitempty" validate:"omitempty"`
}

// #/components/schemas/Pets
type Pets []Pet
