openapi: 3.1.0

info:
    license:
        name: MIT
    title: Swagger Petstore
    version: 1.0.0

servers:
    - url: http://petstore.swagger.io/v1

tags:
    - name: pets

paths:
    /pets:
        get:
            operationId: listPets
            parameters:
                - description: How many items to return at one time (max 100)
                  in: query
                  name: limit
                  required: false
                  schema:
                    format: int32
                    maximum: 100
                    type: integer
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pets'
                    description: A paged array of pets
                    headers: {}
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            summary: List all pets
            tags:
                - pets
        post:
            operationId: createPets
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Pet'
                required: true
            responses:
                "201":
                    description: Null response
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            summary: Create a pet
            tags:
                - pets
    /pets/{petId}:
        get:
            operationId: showPetById
            parameters:
                - description: The id of the pet to retrieve
                  in: path
                  name: petId
                  required: true
                  schema:
                    maxLength: 1
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                    description: Expected response to a valid request
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            summary: Info for a specific pet
            tags:
                - pets

components:
    schemas:
        Error:
            properties:
                code:
                    format: int32
                    type: integer
                message:
                    type: string
            required:
                - code
                - message
            type: object
        Pet:
            description: Pet object
            properties:
                id:
                    format: int64
                    type: integer
                name:
                    description: Pet Name
                    type: string
                tag:
                    description: List of tags
                    type: string
            required:
                - id
                - name
            type: object
        Pets:
            items:
                $ref: '#/components/schemas/Pet'
            maxItems: 100
            type: array